version: "3.0"
services:
# https://github.com/openapitools/openapi-generator-cli     
  openapi-generator-server:
    image: openapitools/openapi-generator-cli
    volumes:
      - ./:/local
    command: generate -g typescript-axios -i /local/openapi.yaml -o /local/client/src/api/generated